name: Deploy to Dev

on:
    push:
      branches:
        - main

jobs:
  build_and_deploy:
    environment:
      name: firebase
      url: "https://dev-creche-casa-do-caminho.web.app"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular
        run: ng build --configuration development

      - name: Deploy to Firebase
        run: npm install -g firebase-tools@latest
      - run: firebase deploy --only hosting:dev --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
